import "./globals.css";
import Navbar from "./components/navbar/page";
import Footer from './components/footer/page'

import '../app/globals.css';
import { arsenal } from '../app/ui/font';

<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={`${arsenal.className} antialiased`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
